stages:
  download_data:
    cmd: make make_data
    deps:
    - src/data/make_dataset.py
    outs:
    - data/raw
  split_data:
    cmd: make split_data
    deps:
    - src/data/split_data.py
    - data/raw
    params:
    - split_data.test_size
    - split_data.stratify
    - split_data.random_state
    outs:
    - data/interim
  build_features:
    cmd: make build_features
    deps:
    - src/features/build_features.py
    - data/interim
    params:
    - build_features.target
    - build_features.cat_feature
    - build_features.num_feature
    outs:
    - data/processed
  train_model:
    cmd: make train_model
    deps:
    - src/models/train_model.py
    - data/processed
    params:
    - train_model.target
    outs:
    - models
  evaluate_model:
    cmd: make evaluate_model
    deps:
    - src/models/evaluate_model.py
    - data/processed
    - models
    params:
    - evaluate_model.target
    outs:
    - reports
