name: CML train & evaluate model
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check directory
        uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: cml
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          make requirements
          # Reproduce pipeline if any changes detected in dependencies
          dvc repro
          echo "MODEL METRICS"
          cat reports/metrics.csv
          # Use DVC metrics diff to compare metrics to main
          git fetch --prune --unshallow
          echo "## Metrics" > report.md
          dvc metrics diff --show-md main >> report.md

